// Generated by https://quicktype.io

import { Asset, RichText } from "../hygraph";

export interface GetAppsResponse {
  apps: App[];
}

export interface App {
  id: string;
  avatar: Partial<Asset>;
  fullname: string;
  nickname: string;
  email: string;
  phoneNumber: string;
  about: Partial<RichText>;
  greeting: Partial<RichText>;
  menu: Menu[];
  socials: Social[];
  technologies: Technology[];
}

export interface Menu {
  label: string;
  pathname: string;
  slug: null;
  href: string;
}

export interface Social {
  id: string;
  label: string;
  link: string;
  icon: string;
}

export interface Technology {
  id: string;
  label: string;
  link: string;
  media: Partial<Asset>;
}
